### ISSUE TITLE
Cannot assign int to property Flownative\Sentry\SentryClient_Original::$sampleRate of type string

### ISSUE THREAD

**Issue by dmitrijkiltau** [flownative/flow-sentry#26]
I've updated to 1.4.0 and just run the command “sentry:test” to get the error `Cannot assign int to property Flownative\Sentry\SentryClient_Original::$sampleRate of type string`

Seems like the sample rate has to be set as string, but the default value is an int: https://github.com/flownative/flow-sentry/pull/25/files

Workaround: set the sample rate in the configuration to `sampleRate: "1"`

**Comment by kitsunet** [comment]
Thank you for the report, we'll take care ASAP.

@kdambekalns I was about to fix this, but then thought we should just directly expect a float there. We have type casting of variable replacement since a while so you could always do `sampleRate: %env(float):ENVIRONMENT_VARIABLE%`. No need to have strings

**Comment by kdambekalns** [comment]
Oh, I totally missed the type declaration on the `$sampleRate` property! That should be `float` and the cast should definiteky happen in the YAML file as suggested by @kitsunet.

**Comment by kdambekalns** [comment]
No, it should not. It should be a `float` in the class and `1.0` in the YAML. Because using the env var will usually lead to that being `false` becoming `0.0` – most people will not have it set.

**Comment by kdambekalns** [comment]
Like that, maybe?
